### ISSUE TITLE
Contact submission TRAVESTY

### ISSUE THREAD

**Issue by jrd656** [WebAhead5/michaelCatsons#5]
I CAN'T BELIEVE HOW RUBBISH THIS WEBSITE IS. TOTAL WASTE OF MY TIME!!!

https://github.com/WebAhead5/michaelCatsons/blob/master/portfolio/src/html/contactForm.html#L14

![image](https://user-images.githubusercontent.com/51966598/76503511-b9768380-644e-11ea-85c4-b7b726989cf6.png)

I get this error message when I submit the form.

Much love,
James

**Comment by MorisR** [comment]
hi,
really sorry for the inconvenience dear sir,
i'm happy to assure you that our hard working dev team has resolved the issue [here](https://github.com/WebAhead5/michaelCatsons/commit/931f0e5abda46a09115caa99357bb8b430081886) 

best regards,
Moris R.
