### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/michaelCatsons#6]
the content of the README was **awesome** it's a really good README, we just need a few design tweaks so it can later on be used for presentations.

[here's an example of a good README](https://github.com/FAC-Sixteen/week-3-agony-yaunt)

[and if you are interested in github emojis](https://www.webfx.com/tools/emoji-cheat-sheet/)

**Comment by JakePowis** [comment]
Thank you! we've now been sure to add plenty of Emojis and Gifs! 

Issue closed.
