### ISSUE TITLE
CSS classes naming

### ISSUE THREAD

**Issue by Karyum** [WebAhead5/michaelCatsons#7]
https://github.com/WebAhead5/michaelCatsons/blob/master/portfolio/src/style/about.css#L37-L70

by reading the CSS classes i should have some basic understanding of what part of the html they are styling. `.qoo` and `.img` tells me nothing :laughing: (there is also `.mid` which probably means middle of the page i'm guessing)

**Comment by JakePowis** [comment]
Thanks for the feedback, we've now renamed these classes to be more descriptive (.quote, .img-about, .mid-page etc)
