### ISSUE TITLE
Reddit link doesn't work

### ISSUE THREAD

**Issue by jrd656** [WebAhead5/michaelCatsons#9]
Menu bar looks great, but I keep trying to click the reddit link and get sent to some vikings?

[https://github.com/WebAhead5/michaelCatsons/blob/master/portfolio/src/index.html#L65](url)

**Comment by JakePowis** [comment]
Thanks - we've changed the icon in the nav bar to something more neutral/relevant, a future design improvement would be to have the names of the links pop up on hover (e.f About, Team) to make it clearer where the nav bar will take you. Issue Closed.
